name: Build Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
        
      - name: Setup Java JDK
        uses: actions/setup-java@v4.7.0
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      
      - name: Maven Build
        run: mvn -B package -DskipTests --file pom.xml

      - name: Upload Jar
        uses: actions/upload-artifact@v4.6.0
        with:
          name: 1.0.0-SNAPSHOT.jar
          path: target/*.jar
