name: Build and Release

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Setup Java JDK
        uses: actions/setup-java@v4.7.0
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - run: mvn -B package -DskipTests --file pom.xml
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4.6.0
        with:
          name: app-jar
          path: target/*.jar
  release:
    name: Release
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Download Build Artifact
        uses: actions/download-artifact@v4.1.8
        with:
          name: app-jar
          path: target
      - name: Get version
        id: get_version
        run: echo "VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV
      - name: Create release
        uses: softprops/action-gh-release@v2.2.1
        with:
          tag_name: v${{ env.VERSION }}
          files: target/*.jar
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
